//-- IKINEMATICS IP REG MAP
#ifndef IKINEMATICS_REG_MAP_H_
#define IKINEMATICS_REG_MAP_H_

#define AXI_IKINEMATICS_0_DEVICE_ID 0
#define AXI_IKINEMATICS_BASEADDR 0x40000000
#define AXI_IKINEMATICS_HIGHADDR 0x4000FFFF
#define AXI_IKINEMATICS_PAGESIZE AXI_IKINEMATICS_HIGHADDR - AXI_IKINEMATICS_BASEADDR + 1
#define AXI_IKINEMATICS_RMAPSIZE 40

//- Regiter Map
#define AXI_IKINEMATICS_S_AXI_SLV_REG0_OFFSET 0
#define AXI_IKINEMATICS_S_AXI_SLV_REG1_OFFSET 4
#define AXI_IKINEMATICS_S_AXI_SLV_REG2_OFFSET 8
#define AXI_IKINEMATICS_S_AXI_SLV_REG3_OFFSET 12
#define AXI_IKINEMATICS_S_AXI_SLV_REG4_OFFSET 16
#define AXI_IKINEMATICS_S_AXI_SLV_REG5_OFFSET 20
#define AXI_IKINEMATICS_S_AXI_SLV_REG6_OFFSET 24
#define AXI_IKINEMATICS_S_AXI_SLV_REG7_OFFSET 28
#define AXI_IKINEMATICS_S_AXI_SLV_REG8_OFFSET 32
#define AXI_IKINEMATICS_S_AXI_SLV_REG9_OFFSET 36
#define AXI_IKINEMATICS_S_AXI_SLV_REG10_OFFSET 40
#define AXI_IKINEMATICS_S_AXI_SLV_REG11_OFFSET 44
#define AXI_IKINEMATICS_S_AXI_SLV_REG12_OFFSET 48
#define AXI_IKINEMATICS_S_AXI_SLV_REG13_OFFSET 52
#define AXI_IKINEMATICS_S_AXI_SLV_REG14_OFFSET 56
#define AXI_IKINEMATICS_S_AXI_SLV_REG15_OFFSET 60

#endif //IKINEMATICS_REG_MAP_H_