//-- IKINEMATICS IP REG MAP
#ifndef __IKINEMATICS_REG_MAP_H__
#define __IKINEMATICS_REG_MAP_H__

#define AXI_IK_0_DEVICE_ID 0
#define AXI_IK_BASEADDR 0x40000000
#define AXI_IK_HIGHADDR 0x4000FFFF
#define AXI_IK_PAGESIZE AXI_IK_HIGHADDR - AXI_IK_BASEADDR + 1
#define AXI_IK_RMAPSIZE 40
#define AXI_IK_WORDSIZE 4

//- Regiter map offsets in 32-bit word
#define AXI_IK_REG0_OFFSET 0
#define AXI_IK_REG1_OFFSET 1
#define AXI_IK_REG2_OFFSET 2
#define AXI_IK_REG3_OFFSET 3
#define AXI_IK_REG4_OFFSET 4
#define AXI_IK_REG5_OFFSET 5
#define AXI_IK_REG6_OFFSET 6
#define AXI_IK_REG7_OFFSET 7
#define AXI_IK_REG8_OFFSET 8
#define AXI_IK_REG9_OFFSET 9
#define AXI_IK_REG10_OFFSET 10
#define AXI_IK_REG11_OFFSET 11
#define AXI_IK_REG12_OFFSET 12
#define AXI_IK_REG13_OFFSET 13
#define AXI_IK_REG14_OFFSET 14
#define AXI_IK_REG15_OFFSET 15

//- Registers Names
#define AXI_IK_REG_CONTROL      0
#define AXI_IK_REG_LEG_CONTROL  1
#define AXI_IK_REG_X_IN         2
#define AXI_IK_REG_Y_IN         3
#define AXI_IK_REG_Z_IN         4
#define AXI_IK_REG_Q1_OUT       2
#define AXI_IK_REG_Q2_OUT       3
#define AXI_IK_REG_Q3_OUT       4
#define AXI_IK_REG_OFFSET_BASE  5
#define AXI_IK_REG_PWM_BASE     23

//- Control Reg
#define AXI_IK_REG_CONTROL_CLEAR_REG    0x00000000
#define AXI_IK_REG_CONTROL_WRITE_FIFO   0x00000001
#define AXI_IK_REG_CONTROL_TRIGGER      0x00000002
#define AXI_IK_REG_CONTROL_ONE_LEG      0x00000001
#define AXI_IK_REG_CONTROL_MUX_LEG      0x00000000

#endif //__IKINEMATICS_REG_MAP_H__