//-- IKINEMATICS IP REG MAP
#ifndef __IKINEMATICS_REG_MAP_H__
#define __IKINEMATICS_REG_MAP_H__

#define AXI_IK_0_DEVICE_ID 0
#define AXI_IK_BASEADDR 0x40000000
#define AXI_IK_HIGHADDR 0x4000FFFF
#define AXI_IK_PAGESIZE AXI_IK_HIGHADDR - AXI_IK_BASEADDR + 1
#define AXI_IK_RMAPSIZE 40
#define AXI_IK_WORDSIZE 4

//- Regiter map offsets in 32-bit word
#define AXI_IK_REG0_OFFSET 0
#define AXI_IK_REG1_OFFSET 1
#define AXI_IK_REG2_OFFSET 2
#define AXI_IK_REG3_OFFSET 3
#define AXI_IK_REG4_OFFSET 4
#define AXI_IK_REG5_OFFSET 5
#define AXI_IK_REG6_OFFSET 6
#define AXI_IK_REG7_OFFSET 7
#define AXI_IK_REG8_OFFSET 8
#define AXI_IK_REG9_OFFSET 9
#define AXI_IK_REG10_OFFSET 10
#define AXI_IK_REG11_OFFSET 11
#define AXI_IK_REG12_OFFSET 12
#define AXI_IK_REG13_OFFSET 13
#define AXI_IK_REG14_OFFSET 14
#define AXI_IK_REG15_OFFSET 15

//- Registers Names
#define AXI_IK_REG_CONTROL      0
#define AXI_IK_REG_LEG_CTRL     1
#define AXI_IK_REG_X_IN         2
#define AXI_IK_REG_Y_IN         3
#define AXI_IK_REG_Z_IN         4
#define AXI_IK_REG_Q1_OUT       2
#define AXI_IK_REG_Q2_OUT       3
#define AXI_IK_REG_Q3_OUT       4
#define AXI_IK_REG_OFFSET_BASE  5
#define AXI_IK_REG_PWM_BASE     23

//- IP Control & Trigger Register
#define AXI_IK_REG_CONTROL_CLEAR_REG    0x00000000
#define AXI_IK_REG_CONTROL_WRITE_FIFO   0x00000001
#define AXI_IK_REG_CONTROL_TRIGGER      0x00000002
#define AXI_IK_REG_CONTROL_DIRECT_OUT   0x00000004

//- Leg Counter Control Register
#define AXI_IK_REG_LEG_CTR_ONE_LEG      0x00000010
#define AXI_IK_REG_LEG_CTR_MUX_LEG      0x00000000
#define AXI_IK_REG_LEG_CTR_LEG_SEL_O    0
#define AXI_IK_REG_LEG_CTR_LEG_SEL_M    0x00000007
#define AXI_IK_REG_LEG_CTR_SET_LEG_T    0x00000008
#define AXI_IK_REG_LEG_CTR_MODE_O       4
#define AXI_IK_REG_LEG_CTR_MODE_M       0x00000030
#define AXI_IK_REG_LEG_CTR_OUTPUT_O     6
#define AXI_IK_REG_LEG_CTR_OUTPUT_M     0x000000C0
#define AXI_IK_REG_LEG_F2F_READ_MUX_O   9
#define AXI_IK_REG_LEG_F2F_READ_MUX_M   0x00000E00
#define AXI_IK_REG_LEG_PWM_INVERT_O     12
#define AXI_IK_REG_LEG_PWM_INVERT_M     0x3FFFF000

#endif //__IKINEMATICS_REG_MAP_H__